"""add is_closed

Revision ID: 848239d60679
Revises: 667f353bd48c
Create Date: 2025-04-15 04:26:16.505547

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "848239d60679"
down_revision: Union[str, None] = "667f353bd48c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "orders",
        sa.Column(
            "is_closed", sa.Boolean(), server_default="f", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("orders", "is_closed")
    # ### end Alembic commands ###
